[tool.poetry]
name = "datachat"
version = "0.1.0"
description = ""
authors = ["wiseupdata <silvio.liborio@wiseupdata.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
